spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://kidpass-mongodb:27017/users
      host: kidpass-mongodb
      port: 27017
      database: kidpass
      username: admin
      password: admin