spring:
  data:
    mongodb:
      host: mongodb # MongoDB host
      port: 27017 # MongoDB port
      database: kidpass # Database name
      username: admin # Username (if authentication is required)
      password: admin # Password (if authentication is required)