spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost # MongoDB host
      port: 27018 # MongoDB port
      database: kidpass # Database name
      username: admin # Username (if authentication is required)
      password: admin # Password (if authentication is required)